### PR TITLE
trigger a rebuild on v0.6.2

### PR DESCRIPTION
**Pull request by yihming**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* <del>[ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yihming** [comment]
@conda-forge-admin please rerender

**Comment by yihming** [comment]
@dpryan79 I created this PR since I didn't see my old PR #17 got updated for hnswlib in conda-forge channel. I'm not sure if this is the appropriate way to push this update. Could you please guide me on fix this issue? Thanks!

**Comment by dpryan79** [comment]
Weird, not sure what happened there. We'll see if merging this in gets the packages listed again.

**Comment by yihming** [comment]
@dpryan79 Thanks. I'll merge it and see if things work.

**Comment by yihming** [comment]
@dpryan79 It seems merging this PR doesn't work. Where should I report this issue?

**Comment by yihming** [comment]
@dpryan79 Do you know where I should bring this issue?

**Pull request merged**
